version: "3"

services:
  myproject-web:
    container_name: myproject-web
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - myproject-db
    ports:
      - "80:80"
    volumes:
      - "./web/:/var/www/html"

  myproject-db:
    container_name: myproject-db
    image: mysql:5.7
    volumes:
      - "./initdb:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: myproject
      MYSQL_USER: myproject-user
      MYSQL_PASSWORD: i3b26syt
      MYSQL_ROOT_PASSWORD: s95x4y7w

  myproject-pma:
    container_name: myproject-pma
    image: phpmyadmin/phpmyadmin:5.2
    depends_on:
      - myproject-db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: myproject-db
      PMA_USER: root
      PMA_PASSWORD: s95x4y7w